RabbitMQ allows an link:{jdkapi}/java/util/concurrent/ExecutorService.html[ExecutorService] to be supplied for new connections. The service is used to execute consumers. A single connection is used for the entire application and it is configured to use the `consumer` named executor service. The executor can be configured through application configuration. See link:{apimicronaut}scheduling/executor/ExecutorConfiguration.html[ExecutorConfiguration] for the full list of options.

For example:

.Configuring the `consumer` thread pool
[source,yaml]
----
micronaut:
    executors:
        consumer:
            type: fixed
            nThreads: 25
----

If no configuration is supplied, a fixed thread pool with 2 times the amount of available processors is used.

=== Concurrent Consumers

By default a single consumer may not process multiple messages simultaneously. RabbitMQ waits to provide the consumer with a message until the previous message has been acknowledged. Starting in version 3.0.0, a new option has been added to the ann:configuration.rabbitmq.annotation.Queue[] annotation to set the number of consumers that should be registered to RabbitMQ for a single consumer method. This will allow for concurrent execution of the consumers.

snippet::io.micronaut.rabbitmq.docs.consumer.concurrent.ProductListener[tags="imports,clazz", project-base="docs-examples/example"]

<1> The `numberOfConsumers` is set on the annotation
<2> Multiple messages received in a short time window will result in the `threads` collection containing something like `[pool-2-thread-9, pool-2-thread-7, pool-2-thread-10, pool-2-thread-8, pool-2-thread-6]`

IMPORTANT: As with any other case of concurrent execution, operations on data in the instance of the consumer must be thread safe.
