import org.jetbrains.kotlin.gradle.dsl.JvmTarget
plugins {
    id 'io.micronaut.build.internal.rabbitmq-examples'
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.kapt")
    id("org.jetbrains.kotlin.plugin.allopen")
}

micronaut {
    testRuntime "kotest5"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
    }
}
