The example in the quick start presented a trivial definition of an interface that be implemented automatically for you using the ann:configuration.rabbitmq.annotation.RabbitClient[] annotation.

The implementation that powers `@RabbitClient` (defined by the api:configuration.rabbitmq.intercept.RabbitMQIntroductionAdvice[] class) is, however, very flexible and offers a range of options for defining RabbitMQ producers.

== Exchange

The exchange to publish messages to can be provided through the ann:configuration.rabbitmq.annotation.RabbitClient[] annotation. In this example, the client is publishing messages to a custom header exchange called `animals`.

snippet::io.micronaut.rabbitmq.docs.exchange.AnimalClient[tags="imports,clazz", project-base="docs-examples/example"]

<1> The exchange name is provided through the `@RabbitClient` annotation.
<2> The header value is used to route the message to a queue.
<3> A helper method was created to provide the header value automatically.

[.lang-python]
****
Python has no method overloading, so the helper method of the Python example is named `send_animal`. Methods with a body are not implemented by `@RabbitClient` and are invoked as declared.
****

IMPORTANT: Exchanges must already exist before you can publish messages to them.
