To add support for RabbitMQ to an existing project, you should first add the Micronaut RabbitMQ configuration to your build configuration. For example:

dependency:micronaut-rabbitmq[groupId="io.micronaut.configuration"]

=== Creating a RabbitMQ Producer with @RabbitClient

To create a RabbitMQ client that produces messages you can simply define an interface that is annotated with ann:configuration.rabbitmq.annotation.RabbitClient[].

For example the following is a trivial `@RabbitClient` interface:

.ProductClient.java
[source,java]
----
include::{testsrabbit}quickstart/ProductClient.java[tags=imports, indent=0]

include::{testsrabbit}quickstart/ProductClient.java[tags=clazz, indent=0]
----

<1> The ann:configuration.rabbitmq.annotation.RabbitClient[] annotation is used to designate this interface as a client
<2> The ann:configuration.rabbitmq.annotation.Binding[] annotation indicates which binding or routing key the message should be routed to.
<3> The 'send' method accepts single parameter which is the body of the message.


At compile time Micronaut will produce an implementation of the above interface. You can retrieve an instance of `ProductClient` either by looking up the bean from the link:{apimicronaut}context/ApplicationContext.html[ApplicationContext] or by injecting the bean with `@Inject`:

.Using ProductClient
[source,java]
----
include::{testsrabbit}quickstart/QuickstartSpec.groovy[tags=producer, indent=0]
----


Note that since the `send` method returns `void` this means the method will publish the message and return immediately without any acknowledgement from the broker.


=== Creating a RabbitMQ Consumer with @RabbitListener

To listen to RabbitMQ messages you can use the ann:configuration.rabbitmq.annotation.RabbitListener[] annotation to define a message listener.

The following example will listen for messages published by the `ProductClient` in the previous section:

.ProductListener.java
[source,java]
----
include::{testsrabbit}quickstart/ProductListener.java[tags=imports, indent=0]

include::{testsrabbit}quickstart/ProductListener.java[tags=class, indent=0]
----

<1> The ann:configuration.rabbitmq.annotation.RabbitListener[] is used to designate the bean as a message listener.
<2> The ann:configuration.rabbitmq.annotation.Queue[] annotation is used to indicate which queue to subscribe to.
<3> The `receive` method accepts a single parameter which is the body of the message.