This library supports RPC through the usage of link:https://www.rabbitmq.com/direct-reply-to.html[direct reply-to]. Both blocking and non blocking variations are supported. To get started using this feature, publishing methods must have the `replyTo` property set to "amq.rabbitmq.reply-to". The "amq.rabbitmq.reply-to" queue always exists and does not need to be created.

The following is an example direct reply to where the consumer is converting the body to upper case and replying with the converted string.

== Client Side

The "client side" in this case starts by publishing a message. A consumer somewhere will then receive the message and reply with a new value.

snippet::io.micronaut.rabbitmq.docs.rpc.ProductClient[tags="imports,clazz", project-base="docs-examples/example]

<1> The reply to property is set. This could be placed on individual methods.
<2> The send method is blocking and will return when the response is received.
<3> The sendReactive method returns a reactive type that will complete when the response is received. Reactive methods will be executed on the IO thread pool.

IMPORTANT: In order for the publisher to assume RPC should be used instead of just completing when the publish is confirmed, the data type must *not* be `Void`. In both cases above, the data type is `String`. In addition, the `replyTo` property must be set. Queues will not be auto created by specifying a value with `replyTo`. The "amq.rabbitmq.reply-to" queue is special and does not need creating.

== Server Side

The "server side" in this case starts with the consumption of a message, and then a new message is published to the reply to queue.

snippet::io.micronaut.rabbitmq.docs.rpc.ProductListener[tags="imports,clazz", project-base="docs-examples/example]

<1> The reply to property is injected. If the consumer will not always be participating in RPC this could be annotated with `@Nullable` to allow both use cases.
<2> The channel is injected so it can be used. This could be replaced with a method call of another `@RabbitClient`.
<3> The converted message is published to the `replyTo` binding.

NOTE: If the reply publish fails for any reason, the original message will be rejected.

IMPORTANT: RPC consumer methods must never return a reactive type. Because the resulting publish needs to occur on the same thread and only a single item can be emitted, there is no value in doing so.

== Configuration

By default, if an RPC call does not have a response within a https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/configurationreference.html[given time frame], a `TimeoutException` will be thrown or emitted.


