This section will outline any breaking changes between major or milestone releases as well as detail any new features that have been added.

== 1.1.0.RC1

* Configuration surrounding defining connections has been expanded to support a list of addresses for fail over and multiple connections.
* Consumers can now define which connection and executor to use.
* Publishers can now define which connection to use.
* Support for specifying the prefetch limit has been added.

== 1.1.0.M2

* The api:configuration.rabbitmq.serdes.RabbitMessageSerDes[] api has been changed significantly to support setting properties before publishing and deserializing complex types.
* Messages published using the default JSON serialization will now have their content type set to "application/json" if it was not set already.
* A consumer can now bind to the Channel used to consume messages
* Support for Direct Reply-To (RPC) has been added. See <<rpc, the documentation>> for more information.
* A new base class for doing channel initialization has been added to make the process easier. See <<initialization, the documentation>> for more information.
* Support for acknowledging messages with a Boolean return type has been removed.
* Publisher acknowledgements will now be executed on the IO thread pool.

