plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly libs.jsr305 // for "warning: unknown enum constant When.MAYBE"

    testRuntimeOnly mnLogging.logback.classic
}

test {
    useJUnitPlatform()

    jvmArgs '-Duser.country=US'
    jvmArgs '-Duser.language=en'
    failFast = true
}


//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-M7-groovy-5.0")
    }
}
