[versions]
micronaut-docs = '2.0.0'
micronaut = '4.0.0-M1'
micronaut-test = '4.0.0-M1'
groovy = '4.0.10'
spock = '2.3-groovy-4.0'

awaitility = '4.2.0'
caffeine = '3.1.5'
jsr305 = "3.0.2"
junit = '5.9.2'
kotest = '5.5.5'
kotlin = '1.8.20'
rabbit = '5.15.0'
testcontainers = '1.18.0'
managed-amqp-client = '5.17.0'

micronaut-micrometer = "5.0.0-M1"
micronaut-serde = "2.0.0-M1"

[libraries]
managed-amqp-client = { module = 'com.rabbitmq:amqp-client', version.ref = 'managed-amqp-client' }

awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit' }
caffeine = { module = 'com.github.ben-manes.caffeine:caffeine', version.ref = 'caffeine' }
jsr305 = {group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
kotest = { module = 'io.kotest:kotest-runner-junit5', version.ref = 'kotest' }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
micronaut-micrometer-core = { module = 'io.micronaut.micrometer:micronaut-micrometer-core', version = '' }
testcontainers = { module = 'org.testcontainers:testcontainers', version.ref = 'testcontainers' }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = 'testcontainers' }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

[plugins]
kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
kotlin-kapt = { id = 'org.jetbrains.kotlin.kapt', version.ref = 'kotlin' }
