A ann:configuration.rabbitmq.annotation.Queue[] annotation is required for a method to be a consumer of messages from RabbitMQ. Simply apply the annotation to the method and supply the name of the queue you would like to listen to.

IMPORTANT: Queues must already exist before you can listen to messages from them.

snippet::io.micronaut.rabbitmq.docs.parameters.ProductListener[tags="imports,clazz", project-base="docs-examples/example]

<1> The queue annotation is set per method. Multiple methods may be defined with different queues in the same class.

=== Other Options

If multiple RabbitMQ servers have been configured, the name of the server can be set in the ann:configuration.rabbitmq.annotation.Queue[] annotation to designate which connection should be used to listen for messages.

snippet::io.micronaut.rabbitmq.docs.consumer.connection.ProductListener[tags="imports,clazz", project-base="docs-examples/example]

<1> The connection is set on the queue annotation.

NOTE: The `connection` option is also available to be set on the ann:configuration.rabbitmq.annotation.RabbitListener[] annotation.

By default all consumers are executed on the same "consumer" thread pool. If for some reason one or more consumers should be executed on a different thread pool, it can be specified on the ann:configuration.rabbitmq.annotation.Queue[] annotation.

snippet::io.micronaut.rabbitmq.docs.consumer.executor.ProductListener[tags="imports,clazz", project-base="docs-examples/example]

<1> The executor is set on the queue annotation.

Micronaut will look for an link:{jdkapi}/java/util/concurrent/ExecutorService.html[ExecutorService] bean with a named qualifier that matches the name set in the annotation. The bean can be provided manually or created automatically through configuration of an link:{apimicronaut}io/micronaut/scheduling/executor/ExecutorConfiguration[].

For example:

.Configuring the `product-listener` thread pool
[source,yaml]
----
micronaut:
    executors:
        product-listener:
            type: fixed
            nThreads: 25
----

NOTE: Due to the way the RabbitMQ Java client works, the initial callback for all consumers is still the thread pool configured in the connection (by default "consumer"), however the work is immediately shifted to the requested thread pool. The `executor` option is also available to be set on the ann:configuration.rabbitmq.annotation.RabbitListener[] annotation.

TIP: The ann:configuration.rabbitmq.annotation.Queue[] annotation supports additional options for consuming messages including declaring the consumer as exclusive, whether to re-queue rejected messages, or set an unacknowledged message limit.